name: "💡 Запрос нового мода / Mod request"
description: "Предложите новый мод на FPS или графику для добавления в Ultimate Optimization"
title: "[Mod Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### 💡 Предложение мода для Ultimate Optimization / Mod suggestion form
  - type: input
    id: mod_name
    attributes:
      label: "1. Название мода / Mod Name"
      placeholder: "Например: Lithium, Sodium, Bobby..."
    validations:
      required: true
  - type: input
    id: mod_link
    attributes:
      label: "2. Ссылка на сайт мода (Любой сайт) / Mod Link (Any site)"
      placeholder: "https://..."
    validations:
      required: true
  - type: textarea
    id: reasoning
    attributes:
      label: "3. Зачем этот мод нужен в сборке? / Why should it be added?"
      placeholder: "Этот мод оптимизирует работу чанков, уменьшает нагрузку на процессор и поднимает FPS..."
    validations:
      required: true
  - type: dropdown
    id: request_os
    attributes:
      label: "4. Operational System / Операционная система"
      options:
        - "🪟 Windows 10 / 11"
        - "🐧 Linux"
        - "🍏 MacOS"
        - "📱 PojavLauncher"
        - "❓ Другая ОС"
    validations:
      required: true
  - type: dropdown
    id: test_drive
    attributes:
      label: "5. На каком накопителе вы тестировали этот мод? / Storage Drive used for testing"
      options:
        - "⚡ SSD / NVMe (Быстрый современный твердотельный накопитель)"
        - "💾 HDD (Обычный старый жесткий диск)"
    validations:
      required: true
  - type: textarea
    id: request_specs_fps
    attributes:
      label: "6. Приблизительный FPS с новым модом, ваши тесты и комплектующие вашего ПК / Your Specs & Test FPS"
      placeholder: "Укажите параметры вашего ПК (Видеокарта, Процессор, SSD/HDD, RAM) и сколько кадров выдает игра после установки этого мода..."
    validations:
      required: true
  - type: checkboxes
    id: user_agreement_request
    attributes:
      label: "⚖️ Пользовательское соглашение / User Agreement"
      options:
        - label: "Я подтверждаю, что предлагаю мод строго для оптимизации, повышения FPS или исправления багов Ultimate Optimization, а не тяжелые контентные моды / I agree to the terms"
          required: true
